# Generated by Django 3.2.7 on 2021-11-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_m_product_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='warehouse_transfer',
        ),
    ]
