# Generated by Django 3.2.7 on 2021-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_delete_warehouse_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_product',
            name='minimum_quantity',
            field=models.FloatField(default=0, verbose_name='Critical Product Quantity'),
        ),
    ]
