# Generated by Django 3.2.7 on 2021-11-27 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_m_product_minimum_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Product List'},
        ),
    ]
