# Generated by Django 3.2.7 on 2021-11-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_m_product_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='m_product_name',
            new_name='m_brand',
        ),
        migrations.AlterModelOptions(
            name='m_brand',
            options={'verbose_name': 'Brand Name', 'verbose_name_plural': 'Brand Names'},
        ),
        migrations.RenameField(
            model_name='m_product',
            old_name='product_name',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='m_category',
            name='product_name',
        ),
        migrations.AddField(
            model_name='m_product',
            name='name',
            field=models.CharField(default='Old Products', max_length=200),
        ),
    ]
