# Generated by Django 3.2.7 on 2021-11-28 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20211129_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_product',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='batch_id',
            field=models.CharField(default='OLD_BATCH', max_length=200),
        ),
        migrations.AddField(
            model_name='stocks',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='m_product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='stocks',
            unique_together={('product', 'warehouse', 'batch_id')},
        ),
    ]
