# Generated by Django 3.2.7 on 2021-11-28 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20211129_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto_increments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('batch_id', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
