# Generated by Django 3.2.7 on 2021-11-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_increments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_increments',
            name='batch_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auto_increments',
            name='customer_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auto_increments',
            name='supplier_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
