# Generated by Django 3.2.7 on 2021-11-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20211130_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'ordering': ['batch_id', '-quantity', 'date_created'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AddField(
            model_name='m_customer',
            name='custom_id',
            field=models.CharField(default='GENERATING...', max_length=10),
        ),
        migrations.AddField(
            model_name='m_supplier',
            name='custom_id',
            field=models.CharField(default='GENERATING...', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='batch_id',
            field=models.CharField(default='         1', max_length=15),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
