# Generated by Django 3.2.7 on 2021-12-07 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20211130_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='batch_id',
            field=models.CharField(default='000000016', max_length=15),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
