# Generated by Django 3.2.7 on 2022-01-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20211207_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_increments',
            name='salesman_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='batch_id',
            field=models.CharField(default='GENERATING...', max_length=15),
        ),
    ]
