# Generated by Django 3.2.7 on 2022-01-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_alter_m_salesman_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_salesman',
            name='custom_id',
            field=models.CharField(default='GENERATING...', max_length=15),
        ),
    ]
