# To be used with the "REST Client" VS Code extension by Huachao Mao
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client


### Variables
@host=http://127.0.0.1:8000
@username=admin
@email=neo@the.matrix
@password=admin
@token=40cf1aaa23cfa93be61b43bd9f9d73b67d270c77


### Create new account
POST {{host}}/auth/users/
Content-Type: application/json

{
    "username": "{{username}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "re_password": "{{password}}"
}


### Login
POST {{host}}/auth/token/login/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}


### Logout
POST {{host}}/auth/token/logout/
Authorization: Token {{token}}


### Get Customer
GET {{host}}/master/customer-list
Authorization: Token {{{{token}}}}