# Generated by Django 3.2.7 on 2021-11-20 05:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_m_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('debit_or_credit', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(blank='False', choices=[('CASH', 'Cash'), ('BANK', 'Bank')], default='CASH', max_length=20)),
                ('invoice_no', models.CharField(blank=True, max_length=200, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.m_bank')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='master.m_customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='master.m_supplier')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='productAndQuantity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.FloatField(default=1)),
                ('price', models.FloatField(default=0)),
                ('discount_in_percent', models.IntegerField(default=0, verbose_name='Discount %')),
                ('invoice_no', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.m_product')),
            ],
            options={
                'verbose_name': 'Product in Quantity',
                'verbose_name_plural': 'Product And Quantity',
            },
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_no', models.CharField(max_length=200, unique=True)),
                ('payment_received_gt', models.FloatField(default=0)),
                ('payment_due_gt', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='master.m_customer')),
                ('payment', models.ManyToManyField(related_name='sale', to='sale.payments')),
                ('productAndQuantity', models.ManyToManyField(related_name='sale', to='sale.productAndQuantity')),
                ('warehouse', models.ForeignKey(default='Main Warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='master.m_warehouse')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('invoice_no', models.CharField(max_length=200, unique=True)),
                ('payment_paid_gt', models.FloatField(default=0)),
                ('payment_due_gt', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('p_payment', models.ManyToManyField(related_name='purchase', to='sale.payments')),
                ('productAndQuantity', models.ManyToManyField(related_name='purchase', to='sale.productAndQuantity')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='master.m_supplier')),
                ('warehouse', models.ForeignKey(default='Main Warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='master.m_warehouse')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
