# Generated by Django 3.2.7 on 2021-11-07 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_m_product_photo'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 14, 31, 24, 120497)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 14, 31, 24, 120497)),
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('invoice_no', models.CharField(max_length=200, unique=True)),
                ('payment_paid_gt', models.FloatField(default=0)),
                ('payment_due_gt', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 7, 14, 31, 24, 122465))),
                ('productAndQuantity', models.ManyToManyField(related_name='purchase', to='sale.productAndQuantity')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='master.m_supplier')),
                ('warehouse', models.ForeignKey(default='Main Warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='master.m_warehouse')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
