# Generated by Django 3.2.7 on 2021-11-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_transfer_product_warehouse_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse_transfer',
            old_name='product',
            new_name='product_list',
        ),
    ]
