# Generated by Django 3.2.7 on 2021-11-07 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20211107_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 14, 41, 2, 693950)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 14, 41, 2, 695914)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 14, 41, 2, 694948)),
        ),
    ]
