# Generated by Django 3.2.7 on 2021-11-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20211127_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
