# Generated by Django 3.2.7 on 2021-11-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_payments_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productandquantity',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
