# Generated by Django 3.2.7 on 2022-01-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_alter_m_salesman_custom_id'),
        ('sale', '0009_auto_20211207_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='master.m_salesman'),
        ),
    ]
