# Generated by Django 3.2.7 on 2022-01-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_sale_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='productandquantity',
            name='salesman_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Salesman Discount'),
        ),
    ]
